openapi: 3.0.1
info:
  title: '@jupiterone/graph-sysdig'
  description: A graph conversion tool for https://sysdig.com/
  x-cortex-git:
    github:
      repository: JupiterOne/graph-sysdig
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-sysdig'
  x-cortex-service-groups:
    - tier-4
